---
- name: playbook
  become: yes
  tasks:
    - name: update repo
      apt:
        update_cache: yes

    - name: install server
      apt: 
        name: nginx
        state: present

    - name: start nginx
      service:
        name: nginx
        state: started
        enable: yes

    - name: Delete content & directory
      ansible.builtin.file:
        state: absent
        path: /var/www/index.html
        ignore_errors: yes


    - name: Copy file with owner and permissions
      ansible.builtin.copy:
        src: /home/ubuntu/ansible/index.html
        dest: /var/www/html
        mode: '0777'

    - name: Add the user 'bucky' with a specific uid and a primary group of 'admin'
      ansible.builtin.user:
        name: bucky
        comment: Bucky dev
        uid: 1040
        group: admin

    - name: backup logs
      fetch:
        src: /var/log/syslog
        dest: /home/ubuntu/log
